name: 'Algolia Upload Records'
description: 'Upload query data records to Algolia'
author: 1165470968@qq.com
branding:
  icon: 'upload-cloud'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
