name: Algolia Upload Records
on:
    push:
        branches:
            - main
jobs:
    algolia:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 120s
              run: sleep 120
            - uses: actions/checkout@v3
            - name: Get the content of algolia.json as config
              id: algolia_config
              run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
            - name: Push indices to Algolia
              uses: jianshe/knowledge-docs@main
              env:
                  APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
                  API_KEY: ${{ secrets.API_KEY }}
                  CONFIG: ${{ steps.algolia_config.outputs.config }}
